apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: medeasy-db-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: medeasy-db-pv
  storageClassName: medeasy-db