apiVersion: v1
kind: PersistentVolume
metadata:
  name: medeasy-db-pv

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /postgresql/postgres-data
  storageClassName: medeasy-db