apiVersion: v1
kind: Service
metadata:
  name: medeasy-chat-redis-headless
spec:
  clusterIP: None
  selector:
    app: medeasy-chat-redis
  ports:
    - name: tcp
      port: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: medeasy-chat-redis
spec:
  type: NodePort
  selector:
    app: medeasy-chat-redis
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
      nodePort: 30380