apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/elasticsearch/esdata
  storageClassName: es-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-backup-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/elasticsearch/esbackup
  storageClassName: es-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: es-storage
  resources:
    requests:
      storage: 20Gi
  volumeName: es-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: es-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: es-backup-pv