apiVersion: v1
kind: Service
metadata:
  name: medeasy-es-headless
spec:
  clusterIP: None
  selector:
    app: medeasy-es
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: medeasy-es
spec:
  type: NodePort
  selector:
    app: medeasy-es
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 30920
    - name: transport
      port: 9300
      targetPort: 9300
      nodePort: 30930