apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: medeasy-es
spec:
  serviceName: medeasy-es-headless
  replicas: 1
  selector:
    matchLabels:
      app: medeasy-es
  template:
    metadata:
      labels:
        app: medeasy-es
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /usr/share/elasticsearch/data
              chmod -R 775 /usr/share/elasticsearch/data
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: [ "sh", "-c", "ulimit -n 65536" ]
          securityContext:
            privileged: true
        - name: install-nori-plugin
          image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
          command:
            - sh
            - -c
            - |
              elasticsearch-plugin remove analysis-nori || true
              elasticsearch-plugin install analysis-nori
          volumeMounts:
            - name: es-plugins
              mountPath: /usr/share/elasticsearch/plugins
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
          env:
            - name: node.name
              value: "single-node"
            - name: cluster.name
              value: "medeasy-elastic-cluster"
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-secret
                  key: ELASTIC_PASSWORD
            - name: network.host
              value: "0.0.0.0"
            - name: path.repo
              value: "/usr/share/elasticsearch/backup"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: es-backup
              mountPath: /usr/share/elasticsearch/backup
            - name: es-plugins
              mountPath: /usr/share/elasticsearch/plugins
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 500Mi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data-pvc
        - name: es-backup
          persistentVolumeClaim:
            claimName: es-backup-pvc
        - name: es-plugins
          emptyDir: {}