apiVersion: v1
kind: Service

metadata:
  name: medeasy-alarm-service

spec:
  type: NodePort
  selector:
    app: medeasy-alarm-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8081
      nodePort: 30002

